version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: govtech_network
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d govtech_network"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
